[package]
name = "gmath"
license = "MIT"
version = "0.1.0"
authors = ["Elias Sjögreen"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "wasm/lib.rs"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
